shader = "default"
cursor_action_right = "Delete"
cursor_action_left = "Move"
zoom_step_factor = 1.2
matrix_step_size = 0.2
cursor_size = 0.1
particle_size = 0.045
show_cursor = true
shift_smoothness = 0.3
auto_time_step = false
cam_movement_speed = 1.0
time_step = 0.02
brush_power = 100
zoom_smoothness = 0.3
particle_size_independent = false
fullscreen = true
position_setter = "centered"
palette = "Natural Rainbow.map"
